In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv("heart.csv")
df.head()

ModuleNotFoundError: No module named 'pandas'

In [4]:
%pip install pandas numpy

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-macosx_10_15_x86_64.whl.metadata (79 kB)
Collecting numpy
  Downloading numpy-2.5.2-cp314-cp314-macosx_10_15_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-macosx_10_15_x86_64.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 4.3 MB/s  0:00:02m0:00:010:01
Downloading numpy-2.5.2-cp314-cp314-macosx_10_15_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 7.6 MB/s  0:00:02m0:00:0100:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2 [numpy]  WARNING: The scripts f2py and numpy-config are installed in '/Library/Frameworks/Python.framework/Versions/3.14/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.2 pandas-3.0.5

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
import numpy as np
df=pd.read_csv("heart.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'heart.csv'

In [8]:
import os
os.getcwd()

'/Users/apple'

In [9]:
import os 
os.listdir("/Users/apple/Downloads")

['jdk-26_macos-aarch64_bin.dmg',
 'python-3.14.4-macos11.pkg',
 'Visual Studio Code.app',
 'CodeChefBadge.png',
 'Form_pdf_605663500060724.pdf',
 'eclipse-inst-jre-mac64 (1).dmg',
 'supermarketdata',
 '.DS_Store',
 '05Form11issue.pdf',
 'Coursera maths.pdf',
 'Zoom (1).pkg',
 'Mbbs degree certificate.pdf',
 'no.pdf',
 'jdk-26_macos-x64_bin.dmg',
 '.localized',
 'SHR PAN.pdf',
 'eclipse-java-2026-06-R-macosx-cocoa-aarch64 (1).dmg',
 'Untitled (1).pages',
 '20250422_70848AMByGPSMapCamera.jpg',
 'heart.csv',
 'IMG-20240304-WA0025~2.jpg',
 'SendAnywhere_808021.zip',
 'GitHub Desktop .app',
 'Visual Studio Code 3.app',
 'Visual Studio Code 2.app',
 'DOC-20240603-WA0020.pdf',
 'DOC-20240506-WA0018..pdf',
 'events.csv',
 'dd floppy-neonate-according-to-the-site-of-involvement.png',
 'Untitled.pages',
 'cousera chemistry.pdf',
 'cousera ai.pdf',
 'GitHubDesktop-x64.zip',
 'archive.zip',
 'WhatsApp-2.25.36.33.dmg',
 'WhatsApp Image 2025-12-25 at 12.02.46.jpeg',
 'archive (1).zip',
 'EHOPS5845A-2024.pdf',
 '05Form9issue(1).pdf',
 'VSCode-darwin-universal.zip',
 'Untitled (2).pages',
 'IMG_20240817_170521_296.jpg',
 'IMG_220425_GPS4.jpg']

In [10]:
import os 
os.listdir("/Users/apple/Downloads")

['jdk-26_macos-aarch64_bin.dmg',
 'python-3.14.4-macos11.pkg',
 'Visual Studio Code.app',
 'CodeChefBadge.png',
 'Form_pdf_605663500060724.pdf',
 'eclipse-inst-jre-mac64 (1).dmg',
 'supermarketdata',
 '.DS_Store',
 '05Form11issue.pdf',
 'Coursera maths.pdf',
 'Zoom (1).pkg',
 'Mbbs degree certificate.pdf',
 'no.pdf',
 'jdk-26_macos-x64_bin.dmg',
 '.localized',
 'SHR PAN.pdf',
 'eclipse-java-2026-06-R-macosx-cocoa-aarch64 (1).dmg',
 'Untitled (1).pages',
 '20250422_70848AMByGPSMapCamera.jpg',
 'heart.csv',
 'IMG-20240304-WA0025~2.jpg',
 'SendAnywhere_808021.zip',
 'GitHub Desktop .app',
 'Visual Studio Code 3.app',
 'Visual Studio Code 2.app',
 'DOC-20240603-WA0020.pdf',
 'DOC-20240506-WA0018..pdf',
 'events.csv',
 'dd floppy-neonate-according-to-the-site-of-involvement.png',
 'Untitled.pages',
 'cousera chemistry.pdf',
 'cousera ai.pdf',
 'GitHubDesktop-x64.zip',
 'archive.zip',
 'WhatsApp-2.25.36.33.dmg',
 'WhatsApp Image 2025-12-25 at 12.02.46.jpeg',
 'EHOPS5845A-2024.pdf',
 '05Form9issue(1).pdf',
 'VSCode-darwin-universal.zip',
 'Untitled (2).pages',
 'IMG_20240817_170521_296.jpg',
 'IMG_220425_GPS4.jpg']

In [13]:
import pandas as pd
import numpy as np
df=pd.read_csv("/Users/apple/Downloads/heart.csv")

In [14]:
import pandas as pd
import numpy as np
df=pd.read_csv("/Users/apple/Downloads/heart.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [15]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [16]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [18]:
df.shape

(1025, 14)

In [19]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [21]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [22]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [1]:
df["age"].mean()

NameError: name 'df' is not defined

In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("/Users/apple/Downloads/heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
df["age"].mean()

np.float64(54.43414634146342)

In [5]:
df["age"].median()

np.float64(56.0)

In [6]:
df["age"].mode()

0    58
Name: age, dtype: int64

In [7]:
df["age"].var()

np.float64(82.3064500762195)

In [8]:
df["age"].std()

np.float64(9.072290233244278)

In [11]:
df["age"].min()

np.int64(29)

In [12]:
df["age"].max()

np.int64(77)

In [13]:
df["age"].count()

np.int64(1025)

In [14]:
df["age"].unique()

array([52, 53, 70, 61, 62, 58, 55, 46, 54, 71, 43, 34, 51, 50, 60, 67, 45,
       63, 42, 44, 56, 57, 59, 64, 65, 41, 66, 38, 49, 48, 29, 37, 47, 68,
       76, 40, 39, 77, 69, 35, 74])

In [15]:
df["sex"].unique()

array([1, 0])

In [16]:
df["sex"].nunique()

2

In [17]:
df["sex"].value_counts()

sex
1    713
0    312
Name: count, dtype: int64

In [18]:
df.isnull()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1021,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1022,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1023,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1024,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
df.isnull().mean()*100

age         0.0
sex         0.0
cp          0.0
trestbps    0.0
chol        0.0
fbs         0.0
restecg     0.0
thalach     0.0
exang       0.0
oldpeak     0.0
slope       0.0
ca          0.0
thal        0.0
target      0.0
dtype: float64

In [20]:
df.dropna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [22]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1020     True
1021     True
1022     True
1023     True
1024     True
Length: 1025, dtype: bool

In [23]:
df.duplicated().sum()

np.int64(723)

In [25]:
df=df.drop_duplicates()

In [26]:

df.duplicated().sum()

np.int64(0)

In [28]:
df["age"]

0      52
1      53
2      70
3      61
4      62
       ..
723    68
733    44
739    52
843    59
878    54
Name: age, Length: 302, dtype: int64

In [30]:
df[["age","cp"]]

     age  cp
0     52   0
1     53   0
2     70   0
3     61   0
4     62   0
..   ...  ..
723   68   2
733   44   2
739   52   0
843   59   3
878   54   0

[302 rows x 2 columns]

In [31]:
df.iloc[0:5]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [32]:
df[df["age"]>30]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
733,44,0,2,108,141,0,1,175,0,0.6,1,0,2,1
739,52,1,0,128,255,0,1,161,1,0.0,2,1,3,0
843,59,1,3,160,273,0,0,125,0,0.0,2,0,2,0
878,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [34]:
df.sort_values("age")

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
60,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
143,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
12,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
254,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
281,35,1,1,122,192,0,1,174,0,0.0,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
269,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
313,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
99,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
160,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0

In [35]:
df.sort_values("age",ascending=False)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
160,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0
99,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
313,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
287,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
269,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
384,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0
12,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
143,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
60,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1

In [36]:
df.rename(columns={"age":"age_years"})

,age_years,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
733,44,0,2,108,141,0,1,175,0,0.6,1,0,2,1
739,52,1,0,128,255,0,1,161,1,0.0,2,1,3,0
843,59,1,3,160,273,0,0,125,0,0.0,2,0,2,0
878,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [37]:
df.groupby("sex")

In [39]:
df.groupby("sex")["age"].mean()

sex
0    55.677083
1    53.834951
Name: age, dtype: float64

In [40]:
pd.concat([df1,df2])

NameError: name 'df1' is not defined

In [41]:
import os
os.getcwd()

'/Users/apple'

In [42]:
import os
os.listdir()

['program2',
 'fact.c',
 '.eclipse',
 'Music',
 'fileopen.c',
 'stringlen',
 'CDD',
 'array1.c',
 'stringlen2.c',
 'python readme.pdf',
 'Untitled1.ipynb',
 'program10.c',
 'array2',
 '.DS_Store',
 'linarysearch.c',
 'eclipse',
 'program6.c',
 'program8.c',
 '.CFUserTextEncoding',
 'array.c',
 'arraymax',
 'program2.c',
 'gitclasses',
 'Untitled.ipynb',
 '.zshrc',
 'keerthanapython',
 'Pictures',
 'array2.c',
 'str.c',
 'program5.c',
 'Licencepython.pdf',
 '.zsh_history',
 'Java',
 '.p2',
 '.ipython',
 'cprogramslabcycle',
 'Desktop',
 'Library',
 'eclipse-workspace',
 'pythonpratice',
 '.lesshst',
 'function',
 'drjagadish.bellary@gmail.com - Google Drive',
 'array2d.c',
 'stringlen.c',
 'program1.c',
 'arraymax.c',
 '.cups',
 'Adlm',
 'doc.jagadish@gmail.com - Google Drive',
 'binarysearch.c',
 'hackathon',
 'a.out',
 'Public',
 '.idlerc',
 'arrayex1.c',
 'program4.c',
 'keerthana.txt',
 'program12.c',
 'Movies',
 'Applications',
 '.Trash',
 'git1',
 'python1.py',
 '.ipynb_checkpoints',
 '.jupyter',
 'Documents',
 'keerthanajava',
 'datastructures.c',
 '.vscode',
 'keerthanapraticepython',
 'html_tutorial',
 'stringlen3.c',
 'Downloads',
 '.redhat',
 '.gitconfig',
 'program11.c',
 'keerthanapython2',
 'program7.c',
 '.zsh_sessions',
 'Davlab2.ipynb',
 'program3.c',
 'program9.c',
 'keerthanapraticepython1']

In [44]:
import os
os.listdir()

['program2',
 'fact.c',
 '.eclipse',
 'Music',
 'fileopen.c',
 'stringlen',
 'CDD',
 'array1.c',
 'stringlen2.c',
 'python readme.pdf',
 'Untitled1.ipynb',
 'program10.c',
 'array2',
 '.DS_Store',
 'linarysearch.c',
 'eclipse',
 'program6.c',
 'program8.c',
 '.CFUserTextEncoding',
 'array.c',
 'arraymax',
 'program2.c',
 'gitclasses',
 'Untitled.ipynb',
 '.zshrc',
 'keerthanapython',
 'Pictures',
 'array2.c',
 'str.c',
 'program5.c',
 'Licencepython.pdf',
 '.zsh_history',
 'Java',
 '.p2',
 '.ipython',
 'cprogramslabcycle',
 'Desktop',
 'Library',
 'eclipse-workspace',
 'pythonpratice',
 '.lesshst',
 'function',
 'drjagadish.bellary@gmail.com - Google Drive',
 'array2d.c',
 'stringlen.c',
 'program1.c',
 'arraymax.c',
 '.cups',
 'Adlm',
 'doc.jagadish@gmail.com - Google Drive',
 'binarysearch.c',
 'hackathon',
 'a.out',
 'Public',
 '.idlerc',
 'arrayex1.c',
 'program4.c',
 'keerthana.txt',
 'program12.c',
 'Movies',
 'Applications',
 '.Trash',
 'git1',
 'python1.py',
 '.ipynb_checkpoints',
 '.jupyter',
 'Documents',
 'keerthanajava',
 'datastructures.c',
 '.vscode',
 'keerthanapraticepython',
 'html_tutorial',
 'stringlen3.c',
 'Downloads',
 '.redhat',
 '.gitconfig',
 'program11.c',
 'keerthanapython2',
 'program7.c',
 '.zsh_sessions',
 'Davlab2.ipynb',
 'program3.c',
 'program9.c',
 'keerthanapraticepython1']