In [1]:
import os
print(os.getcwd())

/Users/apple

In [2]:
import pandas as pd

df = pd.read_csv(os.path.expanduser("~/Downloads/tested.csv"))

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [3]:
print(df.isnull())

     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
413        False     False   False  False  False   True  False  False   False
414        False     False   False  False  False  False  False  False   False
415        False     False   False  False  False  False  False  False   False
416        False     False   False  False  False   True  False  False   False
417        False     False   False  False  False   True  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False   True     False
2    False   True     False
3    False   True     False
4    False   True     False
..     ...    ...       ...
413  False   True     False
414  False  False     False
415  False   True     False
416  False   True     False
417  False   True     False

[418 rows x 12 columns]

In [4]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [6]:
df.shape

(418, 12)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          418 non-null    str
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 39.3 KB

In [5]:
print("Mean Age:",df['Age'].mean())

Mean Age: 30.272590361445783

In [8]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [9]:
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex       Age  SibSp  \
0                                Kelly, Mr. James    male  34.50000      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.00000      1
2                       Myles, Mr. Thomas Francis    male  62.00000      0
3                                Wirz, Mr. Albert    male  27.00000      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1
..                                            ...     ...       ...    ...
413                            Spector, Mr. Woolf    male  30.27259      0
414                  Oliva y Ocana, Dona. Fermina  female  39.00000      0
415                  Saether, Mr. Simon Sivertsen    male  38.50000      0
416                           Ware, Mr. Frederick    male  30.27259      0
417                      Peter, Master. Michael J    male  30.27259      1

     Parch              Ticket      Fare Cabin Embarked
0        0              330911    7.8292   NaN        Q
1        0              363272    7.0000   NaN        S
2        0              240276    9.6875   NaN        Q
3        0              315154    8.6625   NaN        S
4        1             3101298   12.2875   NaN        S
..     ...                 ...       ...   ...      ...
413      0           A.5. 3236    8.0500   NaN        S
414      0            PC 17758  108.9000  C105        C
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416      0              359309    8.0500   NaN        S
417      1                2668   22.3583   NaN        C

[418 rows x 12 columns]

In [10]:
print(df['Embarked'].isnull().sum())

0

In [3]:
import os
print(os.getcwd())

/Users/apple

In [4]:
import pandas as pd

df = pd.read_csv(os.path.expanduser("~/Downloads/tested.csv"))

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
print("Median Fare:", df['Fare'].median())

df['Fare'] = df['Fare'].fillna(df['Fare'].median())

print(df)

Median Fare: 14.4542
     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]

In [7]:
print(df['Fare'].isnull().sum())

0

In [8]:
data = {
    'Student': ['Anu', 'Ravi', 'Priya', 'Kiran', 'Meena'],
    'Department': ['CSE', 'ECE', None, 'ISE', None]
}

df2 = pd.DataFrame(data)

print("Before Forward Fill:")
print(df2)

df2['Department'] = df2['Department'].ffill()

print("\nAfter Forward Fill:")
print(df2)

Before Forward Fill:
  Student Department
0     Anu        CSE
1    Ravi        ECE
2   Priya        NaN
3   Kiran        ISE
4   Meena        NaN

After Forward Fill:
  Student Department
0     Anu        CSE
1    Ravi        ECE
2   Priya        ECE
3   Kiran        ISE
4   Meena        ISE

In [10]:
!pip install scikit-learn

zsh:1: command not found: pip

In [11]:
import sys
!{sys.executable} -m pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp314-cp314-macosx_10_15_x86_64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (2.5.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp314-cp314-macosx_10_15_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp314-cp314-macosx_10_15_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 8.2 MB/s  0:00:01m0:00:01:00:01
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading scipy-1.18.1-cp314-cp314-macosx_10_15_x86_64.whl (31.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.1/31.1 MB 2.9 MB/s  0:00:10m0:00:0100:01
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [scikit-learn][0m [scikit-learn]
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.26.0 scikit-learn-1.9.1 scipy-1.18.1 threadpoolctl-3.7.0

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['Sex_Encoded'] = encoder.fit_transform(df['Sex'])

print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked  Sex_Encoded
0                330911    7.8292   NaN        Q            1
1                363272    7.0000   NaN        S            0
2                240276    9.6875   NaN        Q            1
3                315154    8.6625   NaN        S            1
4               3101298   12.2875   NaN        S            0
..                  ...       ...   ...      ...          ...
413           A.5. 3236    8.0500   NaN        S            1
414            PC 17758  108.9000  C105        C            0
415  SOTON/O.Q. 3101262    7.2500   NaN        S            1
416              359309    8.0500   NaN        S            1
417                2668   22.3583   NaN        C            1

[418 rows x 13 columns]

In [13]:
print(encoder.classes_)

['female' 'male']

In [14]:
encoded_df = pd.get_dummies(df, columns=['Sex'], dtype=int)

print(encoded_df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name   Age  SibSp  Parch  \
0                                Kelly, Mr. James  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  47.0      1      0
2                       Myles, Mr. Thomas Francis  62.0      0      0
3                                Wirz, Mr. Albert  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0      1      1
..                                            ...   ...    ...    ...
413                            Spector, Mr. Woolf   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  39.0      0      0
415                  Saether, Mr. Simon Sivertsen  38.5      0      0
416                           Ware, Mr. Frederick   NaN      0      0
417                      Peter, Master. Michael J   NaN      1      1

                 Ticket      Fare Cabin Embarked  Sex_Encoded  Sex_female  \
0                330911    7.8292   NaN        Q            1           0
1                363272    7.0000   NaN        S            0           1
2                240276    9.6875   NaN        Q            1           0
3                315154    8.6625   NaN        S            1           0
4               3101298   12.2875   NaN        S            0           1
..                  ...       ...   ...      ...          ...         ...
413           A.5. 3236    8.0500   NaN        S            1           0
414            PC 17758  108.9000  C105        C            0           1
415  SOTON/O.Q. 3101262    7.2500   NaN        S            1           0
416              359309    8.0500   NaN        S            1           0
417                2668   22.3583   NaN        C            1           0

     Sex_male
0           1
1           0
2           1
3           1
4           0
..        ...
413         1
414         0
415         1
416         1
417         1

[418 rows x 14 columns]

In [15]:
encoded_df = pd.get_dummies(
    df,
    columns=['Sex'],
    dtype=int
)

print(encoded_df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name   Age  SibSp  Parch  \
0                                Kelly, Mr. James  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  47.0      1      0
2                       Myles, Mr. Thomas Francis  62.0      0      0
3                                Wirz, Mr. Albert  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0      1      1
..                                            ...   ...    ...    ...
413                            Spector, Mr. Woolf   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  39.0      0      0
415                  Saether, Mr. Simon Sivertsen  38.5      0      0
416                           Ware, Mr. Frederick   NaN      0      0
417                      Peter, Master. Michael J   NaN      1      1

                 Ticket      Fare Cabin Embarked  Sex_Encoded  Sex_female  \
0                330911    7.8292   NaN        Q            1           0
1                363272    7.0000   NaN        S            0           1
2                240276    9.6875   NaN        Q            1           0
3                315154    8.6625   NaN        S            1           0
4               3101298   12.2875   NaN        S            0           1
..                  ...       ...   ...      ...          ...         ...
413           A.5. 3236    8.0500   NaN        S            1           0
414            PC 17758  108.9000  C105        C            0           1
415  SOTON/O.Q. 3101262    7.2500   NaN        S            1           0
416              359309    8.0500   NaN        S            1           0
417                2668   22.3583   NaN        C            1           0

     Sex_male
0           1
1           0
2           1
3           1
4           0
..        ...
413         1
414         0
415         1
416         1
417         1

[418 rows x 14 columns]